import { createClient } from '@supabase/supabase-js';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export default async function handler(req,res){
 const slug=String(req.query.slug||'');if(!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug))return res.status(404).send('Not found');
 const url=process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL,key=process.env.VITE_SUPABASE_ANON_KEY||process.env.SUPABASE_ANON_KEY;
 if(!url||!key)return res.status(503).send('Unavailable');
 const db=createClient(url,key);const {data:e}=await db.from('podcast_episodes').select('*').eq('slug',slug).eq('status','published').maybeSingle();if(!e)return res.status(404).send('Not found');
 const origin=(process.env.SITE_URL||'https://fromimpacttoincome.com').replace(/\/$/,'');const canonical=`${origin}/podcast/${slug}`;
 let video='';try{const u=new URL(e.youtube_url);let id=null;if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))id=u.pathname.startsWith('/shorts/')?u.pathname.split('/')[2]:u.searchParams.get('v');else if(u.hostname==='youtu.be')id=u.pathname.slice(1);if(id&&/^[\w-]{11}$/.test(id))video=`<iframe title="${esc(e.title)} video" src="https://www.youtube-nocookie.com/embed/${id}" allowfullscreen loading="lazy"></iframe>`;}catch{}
 if(!video&&e.media_url&&/^https:\/\//.test(e.media_url))video=e.media_kind==='audio'?`<audio controls src="${esc(e.media_url)}"></audio>`:`<video controls src="${esc(e.media_url)}"></video>`;
 const schema={'@context':'https://schema.org','@type':'PodcastEpisode',name:e.title,description:e.description,datePublished:e.published_at,url:canonical,partOfSeries:{'@type':'PodcastSeries',name:'From Impact to Income'},creator:{'@type':'Person',name:'Juanita Brazziel'},...(e.guest_name?{contributor:{'@type':'Person',name:e.guest_name}}:{})};
 const json=JSON.stringify(schema).replace(/</g,'\\u003c');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, s-maxage=300');return res.send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(e.title)} | From Impact to Income</title><meta name="description" content="${esc(e.meta_description||e.description)}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:title" content="${esc(e.title)}"><meta property="og:description" content="${esc(e.meta_description||e.description)}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${json}</script><style>body{margin:0;background:#f9f6ee;color:#1c3228;font:18px/1.65 system-ui}header,main{max-width:800px;margin:auto;padding:28px}a{color:#225c46}h1{font:600 clamp(2.5rem,6vw,4.5rem)/1.1 Georgia}iframe,video{width:100%;aspect-ratio:16/9;border:0}article{white-space:pre-wrap}nav{font-size:15px}</style></head><body><header><nav><a href="/">From Impact to Income</a> / <a href="/podcast">Podcast</a></nav></header><main><p>Episode with ${esc(e.guest_name||'Juanita Brazziel')}</p><h1>${esc(e.title)}</h1><p>${esc(e.description)}</p>${video}<article>${esc(e.article)}</article>${e.guest_bio?`<section><h2>Meet ${esc(e.guest_name)}</h2><p>${esc(e.guest_bio)}</p>${Array.isArray(e.guest_links)?e.guest_links.filter(l=>{try{return ['https:','http:'].includes(new URL(l.url).protocol)}catch{return false}}).map(l=>`<p><a rel="noopener noreferrer" href="${esc(l.url)}">${esc(l.label)}</a></p>`).join(''):''}</section>`:''}${e.transcript?`<details><summary>Read transcript</summary><p>${esc(e.transcript)}</p></details>`:''}</main></body></html>`);
}
