import { createClient } from '@supabase/supabase-js';

const esc = value => String(value || '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);

export default async function handler(req, res) {
  const origin = (process.env.SITE_URL || 'https://fromimpacttoincome.com').replace(/\/$/, '');
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;
  let episodes = [];
  if (url && key) {
    const db = createClient(url, key);
    const { data } = await db.from('podcast_episodes').select('slug,title,description,guest_name,published_at').eq('status', 'published').order('published_at', { ascending: false });
    episodes = data || [];
  }
  const schema = JSON.stringify({ '@context': 'https://schema.org', '@type': 'PodcastSeries', name: 'From Impact to Income', description: 'Creator stories about community impact and how products and services earn income.', url: origin + '/podcast', creator: { '@type': 'Person', name: 'Juanita Brazziel' } }).replace(/</g, '\\u003c');
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=0, s-maxage=300');
  res.send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>From Impact to Income Podcast | Juanita Brazziel</title><meta name="description" content="Conversations with creators about the products and services they built, the impact they make, and how they earn income."><link rel="canonical" href="${origin}/podcast"><script type="application/ld+json">${schema}</script><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Fraunces:opsz,wght@9..144,400;9..144,600&display=swap" rel="stylesheet"><style>
  *{box-sizing:border-box}body{margin:0;background:#f8f5ed;color:#26392f;font:18px/1.6 'DM Sans',system-ui,sans-serif}a{color:inherit}a:focus-visible{outline:3px solid #d25691;outline-offset:4px}.container{width:min(1180px,calc(100% - 48px));margin:auto}.site-nav{height:80px;display:flex;align-items:center;justify-content:space-between}.brand{text-decoration:none;font:600 20px/1.1 'Fraunces',Georgia,serif;color:#1d4834}.brand em{display:block;color:#b25431;font-weight:400}.site-nav nav{display:flex;gap:30px;font-size:14px}.site-nav nav a{text-decoration:none}.hero{background:#101511;color:#fffaf0}.hero-grid{min-height:575px;display:grid;grid-template-columns:1.1fr .9fr;align-items:center;gap:40px;padding:58px 0}.eyebrow{font-size:12px;font-weight:600;letter-spacing:.18em;text-transform:uppercase;color:#f8cf56}.hero h1{font:600 clamp(3.2rem,5.5vw,5.6rem)/1.07 'Fraunces',Georgia,serif;letter-spacing:-.03em;max-width:650px;margin:25px 0}.hero p{max-width:560px;color:#ebe5dc;font-size:19px}.hero img{display:block;width:100%;height:auto;max-width:500px;margin:auto}.episodes{padding:66px 0 90px}.episodes .eyebrow{color:#b25431}.episodes h2{font:600 clamp(2.2rem,4vw,3.5rem)/1.2 'Fraunces',Georgia,serif;margin:10px 0 36px}.episode-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.episode{background:#fff;border:1px solid #deded7;padding:30px;border-radius:5px}.episode h3{font:600 2rem 'Fraunces',Georgia,serif;margin:12px 0}.empty{border-top:1px solid #d6d8d0;padding-top:32px;color:#4c5c51}.site-footer{border-top:1px solid #d6d8d0;padding:25px 0;font-size:13px;color:#526256}@media(max-width:700px){.container{width:min(100% - 36px,1180px)}.site-nav{height:70px}.site-nav nav{gap:14px;font-size:12px}.hero-grid{grid-template-columns:1fr;min-height:0;padding:52px 0 44px;gap:16px}.hero h1{font-size:clamp(2.7rem,11vw,4.5rem)}.hero p{font-size:17px}.hero img{max-width:350px}.episode-grid{grid-template-columns:1fr}.episodes{padding:48px 0 68px}}
  </style></head><body><header class="container site-nav"><a class="brand" href="/">From Impact<em>to Income</em></a><nav aria-label="Main navigation"><a href="/journal">Journal</a><a href="/about">About</a><a href="/podcast" aria-current="page">Podcast</a></nav></header><main><section class="hero"><div class="container hero-grid"><div><span class="eyebrow">The podcast with Juanita Brazziel</span><h1>The story behind what you built.</h1><p>Honest conversations with creators about the apps, products, and services changing communities—and the real ways they make that work sustainable.</p></div><img src="/from-impact-to-income-logo.png" alt="From Impact to Income Podcast" width="1254" height="1254"></div></section><section class="container episodes" aria-labelledby="episodes-heading"><span class="eyebrow">Watch · Listen · Read</span><h2 id="episodes-heading">Latest conversations</h2><div class="episode-grid">${episodes.map(episode => `<article class="episode"><span class="eyebrow">${esc(episode.guest_name || 'Solo episode')}</span><h3><a href="/podcast/${esc(episode.slug)}">${esc(episode.title)}</a></h3><p>${esc(episode.description)}</p><a href="/podcast/${esc(episode.slug)}">Watch, listen & read →</a></article>`).join('')}</div>${episodes.length ? '' : '<p class="empty">Episodes are on their way. Come back for the first conversation.</p>'}</section></main><footer class="site-footer"><div class="container">From Impact to Income · Stories of ideas, impact, and sustainable income.</div></footer></body></html>`);
}
