import { createClient } from '@supabase/supabase-js';
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY||!process.env.ANTHROPIC_API_KEY)return res.status(503).json({error:'Article service is not configured'});
 const db=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);
 const token=(req.headers.authorization||'').replace(/^Bearer /,'');const {data:{user},error}=await db.auth.getUser(token);if(error||!user)return res.status(401).json({error:'Sign in required'});
 const {data:admin}=await db.from('podcast_admins').select('user_id').eq('user_id',user.id).maybeSingle();if(!admin)return res.status(403).json({error:'Admin access required'});
 const {title,guest_name,guest_bio,transcript,description}=req.body||{};if(typeof transcript!=='string'||transcript.length<100||transcript.length>100000)return res.status(400).json({error:'Add an interview transcript or detailed notes (100–100,000 characters)'});
 try {const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':process.env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-5',max_tokens:3000,system:'Write a factual, helpful podcast article in Juanita Brazziel’s direct, warm voice. Focus on the guest’s creative process, community impact, and monetization. Use clear subheadings and a brief guest bio. Use only supplied source material. Never invent quotes, claims, revenue figures, links, or outcomes. Return valid JSON with string fields article and meta_description. The latter is at most 160 characters. Do not include the video embed; the page adds it separately.',messages:[{role:'user',content:JSON.stringify({title,guest_name,guest_bio,description,transcript})}]})});const result=await response.json();if(!response.ok)throw Error(result.error?.message||'Generation failed');const raw=result.content?.find(c=>c.type==='text')?.text||'';const parsed=JSON.parse(raw.replace(/^```(?:json)?\s*|\s*```$/g,''));return res.json({article:parsed.article,meta_description:parsed.meta_description});}catch(e){return res.status(502).json({error:e.message||'Generation failed'});}
}
